### ISSUE TITLE
[BUG] Items with "Charges" prevent rests from finishing and don't recharge.

### ISSUE THREAD

**Issue by SirGarhi** [fantasycalendar/FoundryVTT-RestRecovery#123] opened 2023-01-03 23:59 UTC
**Describe the bug**
Items configured with Charges not recharging and preventing rests from finishing.

**To Reproduce**
1. Add an item that has "Charges" as the limited use to a character (specifically tested with Earring of Message and Horn of Silent Alarm)
2. Set the number of current uses to less than the total so that it needs to recover.
3. Click the Long Rest button on the character sheet.
4. Click to Finish the rest, notice that the chat log doesn't summarize the rest and there's an error in the console

**Expected behavior**
The rest finishes as normal and the appropriate formula is applied to recharge the item(s).

**Screenshots**
![RestRecovery](https://user-images.githubusercontent.com/113884133/210460669-74818c91-2289-417b-a331-ed24cab44b04.PNG)

**Setup:**
 - Foundry Version: [10.291]
 - System Version: [DnD5e 2.0.3]
 - Rest Recovery Version: [1.4.6]
 - Browser & version [Foundry Desktop App]

**Active modules:**
 - Rest Recovery
 - libwrapper

**Additional context**
Text of the error:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'push')
[Detected 2 packages: system:dnd5e, rest-recovery]
    at Actor5e._getRestItemUsesRecovery (actor.mjs:1761:17)
    at async RestWorkflow.asyncWrappedFn (rest-workflow.js:575:19)
    at async 🎁CONFIG.Actor.documentClass.prototype._rest#rest-recovery (libwrapper.js:154:14)

**Comment by Haxxer** [comment] 2023-01-05 21:31
I cannot reproduce this - could you upload the item in question?

**Comment by SirGarhi** [comment] 2023-01-05 23:25
[fvtt-Item-horn-of-silent-alarm.txt](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/files/10356227/fvtt-Item-horn-of-silent-alarm.txt)

Here's one that causes it, it's also happening with any of the wands out of the SRD Item Compendium.

After a little more experimenting the problem is actually the standard "Recovery Formula" field, which is only visible and applicable if the item is set to "Charges." If that field is empty then the rest completes as normal but the item doesn't recharge at all, even if you tick the box for custom recovery and fill that field in.

The desired behavior can be replicated as a workaround by setting the item to Long Rest or Day and using the Custom Recovery field, but a lot of pre-built items are set up using Charges and the standard Recovery Formula.

**Comment by Haxxer** [comment] 2023-01-29 21:42
Fixed in 1.4.7, apologies for the wait

**Closed** 2023-02-04 18:50 UTC
Labels: bug
