### ISSUE TITLE
Automation Exhaustion

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-RestRecovery#51] opened 2022-06-01 20:06 UTC
When I have activated the auto exhaustion with the DF confition, when it starts to accumulate exhaustion (more than level 2) things start to get weird and it applies several conditions at the same time.
![image](https://user-images.githubusercontent.com/3178127/171491690-97ced8cf-8266-4846-a60c-21690a44750b.png)

Ideally, if you apply DF effects, not module effects.

The bug is easy to check with DF Convenient effects active, raise exhaustion 3 levels and then try to reduce exhaustion by long rest

**Comment by Haxxer** [comment] 2022-06-01 20:23
Are you sure there's not another module that does that? I only apply one effect, nothing else.

**Comment by Haxxer** [comment] 2022-06-01 20:23
Also please fill in the actual bug template, it's there for a reason

**Comment by rinnocenti** [comment] 2022-06-02 01:20
> Are you sure there's not another module that does that? I only apply one effect, nothing else.

i sure

**Comment by rinnocenti** [comment] 2022-06-02 01:20
> 



> Also please fill in the actual bug template, it's there for a reason

sorry ill

**Comment by Haxxer** [comment] 2022-06-02 22:32
Duplicate of #53

**Closed by Haxxer** 2022-06-02 22:32 UTC
Labels: bug
