### ISSUE TITLE
[BUG] Food&Water Consumtion not working if not set to "One charge worth entire day worth"

### ISSUE THREAD

**Issue by DevConFox** [fantasycalendar/FoundryVTT-RestRecovery#158] opened 2023-09-17 10:51 UTC
**Describe the bug**
If the consumable item is not set for an entiry day worth, the food and water automation will not work. The item can be selected during the long rest menu and the cost can be set accordingly. However, even if the menu indicates that everything is consumed to satisfy hunger/thirst, finishing the long rest will result in exhaustion.

**To Reproduce**
1. Set up food & water automation (required units 1 food / 1 water) and exhaustion automation (using DFreds CE)
2. Create consumable item. Declare as water, set charges to 4/4. Do NOT set to be worth entire day worth.
3. Prompt for long rest. Grant external food source and add water consumable to be used.
4. Finish long rest. Chat message reads "They did not drink anything. Thus, they suffered 1 levels of exhaustion". The item loses a charge. In case the item's charges are set to 1/1, it loses 2 stacks of quantity. See: #156 
5. This bug is even more confusing if the setting for food & water is set to more than 1 unit.

**Expected behavior**
The correct amount of charges to be used and exhaustion not to be added

**Setup:**
 - Foundry Version: 11.308
 - System Version: DND5e 2.3.1
 - Rest Recovery Version: 1.4.13
 - Browser & version: Google Chrome 116.0.5845.188

**Active modules:**
 - Rest Recovery
 - libwrapper 1.12.13.0
 - socketlib 1.0.13
 - DFreds CE 5.1.0
 - Simple Calendar 2.4.0

**Comment by Haxxer** [comment] 2023-09-17 12:40
Duplicate? https://github.com/fantasycalendar/FoundryVTT-RestRecovery/issues/156

**Comment by DevConFox** [comment] 2023-09-17 13:16
Unclear.

 #156 deals with the problem of quantity discrepancies, while this issue aims to address problems with charge consumption.
Both problems could have the same origin, be partly overlapping or be two aspects of a wider problem.

**Comment by Haxxer** [comment] 2023-09-24 17:05
@DevConFox Odd, I can't reproduce this.

![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/12858387/08f58b04-6461-4c0a-9482-954aefee829a)

![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/12858387/e885d8ab-0a6e-4a7f-9598-19315cebc323)

**Comment by Haxxer** [comment] 2023-09-24 17:58
Fixed in 1.4.14

**Closed by Haxxer** 2023-09-24 17:58 UTC
Labels: bug

**Comment by FKoenig-FL** [comment] 2023-10-01 10:33
@Haxxer There still seems to be an issue regarding charge usage and exhaustion. I took a short screen capture demonstrating the effect:
https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/60885915/b0fd7d0f-223d-49c8-8ce5-1939287b4dbd
